"""
Agent Manager for handling multiple trading agents.
Implements the strategy pattern for agent switching.
"""

from typing import Dict, List, Optional, Any
from loguru import logger
from datetime import datetime

from .interfaces import IAgentManager, ITradingAgent, TradingSignal, MarketData
from ..core.exceptions import AgentNotFoundError, AgentInitializationError


class AgentManager(IAgentManager):
    """Manages multiple trading agents with easy switching capability."""

    def __init__(self):
        self._agents: Dict[str, ITradingAgent] = {}
        self._active_agent: Optional[str] = None  # For backward compatibility (single agent mode)
        self._active_agents: List[str] = []  # For multi-agent mode
        self._agent_configs: Dict[str, Dict[str, Any]] = {}
        self._multi_agent_mode: bool = False  # False = single agent, True = multiple agents

    def register_agent(self, agent: ITradingAgent, config: Optional[Dict[str, Any]] = None) -> None:
        """Register a new trading agent."""
        agent_name = agent.get_name()

        try:
            if config:
                agent.initialize(config)
                self._agent_configs[agent_name] = config

            self._agents[agent_name] = agent
            logger.info(f"Agent '{agent_name}' registered successfully")

        except Exception as e:
            logger.error(f"Failed to register agent '{agent_name}': {e}")
            raise AgentInitializationError(f"Agent initialization failed: {e}")

    def unregister_agent(self, agent_name: str) -> None:
        """Unregister a trading agent."""
        if agent_name not in self._agents:
            raise AgentNotFoundError(f"Agent '{agent_name}' not found")

        if self._active_agent == agent_name:
            self._active_agent = None

        del self._agents[agent_name]
        if agent_name in self._agent_configs:
            del self._agent_configs[agent_name]

        logger.info(f"Agent '{agent_name}' unregistered")

    def set_active_agent(self, agent_name: str) -> bool:
        """Set the active trading agent."""
        if agent_name not in self._agents:
            raise AgentNotFoundError(f"Agent '{agent_name}' not found")

        self._active_agent = agent_name
        logger.info(f"Active agent set to '{agent_name}'")
        return True

    def get_active_agent(self) -> Optional[ITradingAgent]:
        """Get the currently active trading agent."""
        if self._active_agent is None:
            return None
        return self._agents.get(self._active_agent)

    def get_agent(self, agent_name: str) -> ITradingAgent:
        """Get a specific agent by name."""
        if agent_name not in self._agents:
            raise AgentNotFoundError(f"Agent '{agent_name}' not found")
        return self._agents[agent_name]

    def list_agents(self) -> List[str]:
        """List all registered agent names."""
        return list(self._agents.keys())

    def get_agent_info(self, agent_name: str) -> Dict[str, Any]:
        """Get information about a specific agent."""
        if agent_name not in self._agents:
            raise AgentNotFoundError(f"Agent '{agent_name}' not found")

        agent = self._agents[agent_name]
        return {
            "name": agent.get_name(),
            "description": agent.get_description(),
            "parameters": agent.get_parameters(),
            "is_active": agent_name == self._active_agent,
            "config": self._agent_configs.get(agent_name, {})
        }

    async def analyze_with_active_agent(self, market_data: List[MarketData]) -> Optional[TradingSignal]:
        """Analyze market data using the active agent."""
        active_agent = self.get_active_agent()
        if active_agent is None:
            logger.warning("No active agent set")
            return None

        try:
            signal = await active_agent.analyze(market_data)
            logger.info(f"Signal generated by '{self._active_agent}': {signal.action} {signal.symbol}")
            return signal

        except Exception as e:
            logger.error(f"Error analyzing with agent '{self._active_agent}': {e}")
            return None

    async def analyze_with_agent(self, agent_name: str, market_data: List[MarketData]) -> TradingSignal:
        """Analyze market data using a specific agent."""
        agent = self.get_agent(agent_name)

        try:
            signal = await agent.analyze(market_data)
            logger.info(f"Signal generated by '{agent_name}': {signal.action} {signal.symbol}")
            return signal

        except Exception as e:
            logger.error(f"Error analyzing with agent '{agent_name}': {e}")
            raise

    def update_agent_config(self, agent_name: str, config: Dict[str, Any]) -> None:
        """Update configuration for a specific agent."""
        if agent_name not in self._agents:
            raise AgentNotFoundError(f"Agent '{agent_name}' not found")

        try:
            agent = self._agents[agent_name]
            agent.initialize(config)
            self._agent_configs[agent_name] = config
            logger.info(f"Configuration updated for agent '{agent_name}'")

        except Exception as e:
            logger.error(f"Failed to update configuration for agent '{agent_name}': {e}")
            raise AgentInitializationError(f"Agent configuration update failed: {e}")

    def get_agent_status(self) -> Dict[str, Any]:
        """Get status of all agents."""
        return {
            "total_agents": len(self._agents),
            "active_agent": self._active_agent,
            "active_agents": self._active_agents,
            "multi_agent_mode": self._multi_agent_mode,
            "agents": [self.get_agent_info(name) for name in self._agents.keys()]
        }

    # Multi-agent mode methods

    def enable_multi_agent_mode(self) -> None:
        """Enable multi-agent mode."""
        self._multi_agent_mode = True
        logger.info("Multi-agent mode enabled")

    def disable_multi_agent_mode(self) -> None:
        """Disable multi-agent mode and return to single agent mode."""
        self._multi_agent_mode = False
        self._active_agents = []
        logger.info("Multi-agent mode disabled")

    def set_active_agents(self, agent_names: List[str]) -> bool:
        """
        Set multiple active agents for multi-agent mode.

        Args:
            agent_names: List of agent names to activate

        Returns:
            True if successful

        Raises:
            AgentNotFoundError: If any agent not found
        """
        # Validate all agents exist
        for name in agent_names:
            if name not in self._agents:
                raise AgentNotFoundError(f"Agent '{name}' not found")

        self._active_agents = agent_names
        self._multi_agent_mode = True

        # For backward compatibility, set first agent as single active agent
        if agent_names:
            self._active_agent = agent_names[0]

        logger.info(f"Active agents set to: {', '.join(agent_names)}")
        return True

    def add_active_agent(self, agent_name: str) -> bool:
        """
        Add an agent to the active agents list.

        Args:
            agent_name: Name of agent to add

        Returns:
            True if successful
        """
        if agent_name not in self._agents:
            raise AgentNotFoundError(f"Agent '{agent_name}' not found")

        if agent_name not in self._active_agents:
            self._active_agents.append(agent_name)
            self._multi_agent_mode = True
            logger.info(f"Added '{agent_name}' to active agents")

        return True

    def remove_active_agent(self, agent_name: str) -> bool:
        """
        Remove an agent from the active agents list.

        Args:
            agent_name: Name of agent to remove

        Returns:
            True if successful
        """
        if agent_name in self._active_agents:
            self._active_agents.remove(agent_name)
            logger.info(f"Removed '{agent_name}' from active agents")

            # If no agents left, disable multi-agent mode
            if not self._active_agents:
                self._multi_agent_mode = False

        return True

    def get_active_agents(self) -> List[ITradingAgent]:
        """
        Get all currently active agents.

        Returns:
            List of active agent instances
        """
        if not self._multi_agent_mode:
            # Single agent mode - return single agent as list for consistency
            agent = self.get_active_agent()
            return [agent] if agent else []

        return [self._agents[name] for name in self._active_agents if name in self._agents]

    def is_multi_agent_mode(self) -> bool:
        """Check if multi-agent mode is enabled."""
        return self._multi_agent_mode

    async def analyze_with_all_agents(self, market_data: List[MarketData]) -> Dict[str, TradingSignal]:
        """
        Analyze market data with all active agents.

        Args:
            market_data: Market data to analyze

        Returns:
            Dictionary mapping agent names to their signals
        """
        results = {}
        active_agents = self.get_active_agents()

        for agent in active_agents:
            try:
                signal = await agent.analyze(market_data)
                results[agent.get_name()] = signal
                logger.debug(f"Signal from '{agent.get_name()}': {signal.action} {signal.symbol}")
            except Exception as e:
                logger.error(f"Error analyzing with agent '{agent.get_name()}': {e}")

        return results